/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_roytrack_dailytest_jni_JNICall */

#ifndef _Included_com_roytrack_dailytest_jni_JNICall
#define _Included_com_roytrack_dailytest_jni_JNICall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_roytrack_dailytest_jni_JNICall
 * Method:    CallTheDll
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_roytrack_dailytest_jni_JNICall_CallTheDll
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
